- name: "bug"
  color: "990000"
  description: "Hightlights an error or bug in the codebase."
- name: "enhancement"
  color: "a2eeef"
  description: "Indicates an improvement to existing features of the codebase."
- name: "feature request"
  color: "31194B"
  description: "Highlights proposals for new enhancements or features."
- name: "documentation"
  color: "286129"
  description: "Improvements or additions to the documentation."
- name: "question"
  color: "86B7A4"
  description: "Reserved for questions or discussions rather than specific issues or code changes."
- name: "duplicate"
  color: "f2f2f2"
  description: "Signifies that the subject has been raised elsewhere in the repository."
- name: "invalid"
  color: "2d3436"
  description: "Indicates something invalid or no longer relevant."
- name: "wontfix"
  color: "666633"
  description: "Indicates that the issue will not be addressed or resolved for a specific reason."
- name: "status: needs repro"
  color: "807E14"
  description: "Applied to issues or bug reports that require additional details or clear steps to reproduce."
- name: "status: needs fix"
  color: "ffd24d"
  description: "Applied to issues or bug reports that have been identified as requiring code changes or fixes."
