name: Feature Request
description: File a feature request.
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for showing desire to improve our project by suggesting a feature. Please fill out the details below to help us understand your request.
  - type: textarea
    id: feature-details
    attributes:
      label: Feature Details
      description: Please precisely describe the feature you'd like to propose.
      placeholder: Feature details...
    validations:
      required: true
  - type: checkboxes
    id: bug-origin
    attributes:
      label: Linked to Issue
      description: Is this feature request related to a problem?
      options:
        - label: The request is related to a problem.
          required: false
  - type: textarea
    id: problem-details
    attributes:
      label: Problem Details
      description: Please precisely describe the problem you've been experiencing.
      placeholder: Problem details...
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered.
      placeholder: Alternative solutions...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Let us know if there is any additional context we should know about.
      placeholder: Additional context...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]().
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
